services:
  account:
    container_name: account-service
    build:
      context: ../
      dockerfile: docker/account-service.dockerfile
      target: release
    depends_on:
      - nats
      - mongo

  agent:
    container_name: agent-service
    build:
      context: ../
      dockerfile: docker/agent-service.dockerfile
      target: release
    depends_on:
      - nats

  auth:
    container_name: auth-service
    build:
      context: ../
      dockerfile: docker/auth-service.dockerfile
      target: release
    depends_on:
      - nats

  channel:
    container_name: channel-service
    build:
      context: ../
      dockerfile: docker/channel-service.dockerfile
      target: release
    depends_on:
      - nats

  gateway:
    container_name: gateway-service
    build:
      context: ../
      dockerfile: docker/gateway-service.dockerfile
      target: release
    ports:
      - '3000:3000'
    depends_on:
      - nats
      - account
      - auth
      - channel
      - agent

  mongo:
    image: mongo

  nats:
    image: nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command: -js
