services:
  account:
    container_name: account-service
    build:
      tags:
        - account-service
      context: ../
      dockerfile: docker/account-service.dockerfile
      target: release
    env_file:
      - ../apps/account/.env
    depends_on:
      - nats
      - mongo

  user:
    container_name: user-service
    build:
      context: ../
      dockerfile: docker/user-service.dockerfile
      target: release
    env_file:
      - ../apps/user/.env
    depends_on:
      - nats

  auth:
    container_name: auth-service
    build:
      context: ../
      dockerfile: docker/auth-service.dockerfile
      target: release
    env_file:
      - ../apps/auth/.env
    depends_on:
      - nats

  channel:
    container_name: channel-service
    build:
      context: ../
      dockerfile: docker/channel-service.dockerfile
      target: release
    env_file:
      - ../apps/channel/.env
    depends_on:
      - nats

  gateway:
    container_name: gateway-service
    build:
      context: ../
      dockerfile: docker/gateway-service.dockerfile
      target: release
    env_file:
      - ../apps/gateway/.env
    ports:
      - '3000:3000'
    depends_on:
      - nats
      - account
      - auth
      - channel
      - user

  mongo:
    image: mongo
    container_name: admin-mongodb

  nats:
    image: nats
    container_name: admin-nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command: -js
