services:
  project-service:
    container_name: project-service
    build:
      tags:
        - project-service
      context: ../
      dockerfile: project-service.dockerfile
      target: release
    env_file:
      - ../apps/project/.env
    depends_on:
      - nats
      - mongo

  user-service:
    container_name: user-service
    build:
      context: ../
      dockerfile: docker/user-service.dockerfile
      target: release
    env_file:
      - ../apps/user/.env
    depends_on:
      - nats

  auth-service:
    container_name: auth-service
    build:
      context: ../
      dockerfile: docker/auth-service.dockerfile
      target: release
    env_file:
      - ../apps/auth/.env
    depends_on:
      - nats
      -
  gateway-service:
    container_name: gateway-service
    build:
      context: ../
      dockerfile: docker/gateway-service.dockerfile
      target: release
    env_file:
      - ../apps/gateway/.env
    ports:
      - '3000:3000'
    depends_on:
      - nats
      - project-service
      - auth-service
      - user-service

  mongo:
    image: mongo
    container_name: admin-mongodb

  nats:
    image: nats
    container_name: admin-nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command: -js
